### ISSUE TITLE
A part of conditional expression is always false

### ISSUE THREAD

**Issue by thehlopster** [NMan1/OverflowTF2#1]
```cpp
uint32_t index
```

https://github.com/NMan1/OverflowTF2/blob/54ec88f65472c3cf7ddb180b9a65b562dd44023d/core/utils/memory/memory.hpp#L71
https://github.com/NMan1/OverflowTF2/blob/54ec88f65472c3cf7ddb180b9a65b562dd44023d/core/utils/memory/memory.hpp#L80
https://github.com/NMan1/OverflowTF2/blob/54ec88f65472c3cf7ddb180b9a65b562dd44023d/core/utils/memory/memory.hpp#L88
```cpp
typedef unsigned int       uint32_t;
```
since uint32_t is unsigned it is never lower than 0, so this check is unnecessary and can be removed

**Comment by NMan1** [comment]
thank you
