### ISSUE TITLE
[Skid Question] How To Get Offests?

### ISSUE THREAD

**Issue by PlavnikHacks** [NMan1/OverflowTF2#4]
I have my own cheat i made but to be honest i got no clue how to get offsets for tf2, i know how to get them for other singleplayer games but i dont wanna wait or bug other people to get me offsets. You can just close this if you dont wanna help but please, ive been looking for days on how to get offsets and you seem like an experienced developer. So will you please tell me how to get offsets for tf2?

**Comment by NMan1** [comment]
Well this is an internal cheat so the games interfaces are being used, but if your talking about an external cheat just use a dumper ([like this one](https://github.com/ActualDragonTears/TF2-Offset-Dumper)). The offsets are just netvars which can be dumped easily using tools. Look at netvar dumpers. [video for u](https://youtu.be/hBA-_aAETX4)

**Comment by PlavnikHacks** [comment]
Thank you bro helped a lot, used the cheat very awesome! The aimbot not the best though but it works! Thanks again :)

**Comment by im-fin** [comment]
sa

**Comment by im-fin** [comment]
a
