### ISSUE TITLE
esp only draws close to targets?

### ISSUE THREAD

**Issue by dontbestupid** [NMan1/OverflowTF2#7]
Hello NMan1,

i tried to get this chair working. i managed to fix the crash since latest tf update, also the aimbot works pretty well.
but now i stuck at the point that esp only draws when im really close to the target.
i was wondering if you could give me a hint what it could be? would be glad

https://gyazo.com/f39c46ae032c710d9b5300e330e86c09

Greetings

**Comment by NMan1** [comment]
That’s defiently a weird issue. I would first start by debugging the esp run function, stepping through each line to see where the code fails. 

If I had to guess off the top of my head perhaps get_item_bounds is failing, maybe a world to screen issue. Debugging the code will show you what’s causing the problem
